### ISSUE TITLE
A bug occurred while running train.py

### ISSUE THREAD

**Issue by yysube** [cvlab-stonybrook/DM-Count#27]
train.py is not running and encounters the following problems.
in pytorch 1.2

Traceback (most recent call last):
  File "C:/Program Files (x86)/DM-Count-master/train.py", line 64, in <module>
    trainer.train()
  File "C:\Program Files (x86)\DM-Count-master\train_helper.py", line 110, in train
    self.train_eopch()
  File "C:\Program Files (x86)\DM-Count-master\train_helper.py", line 126, in train_eopch
    for step, (inputs, points, gt_discrete) in enumerate(self.dataloaders['train']):
  File "C:\Anaconda\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\Anaconda\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\Anaconda\envs\py37\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Anaconda\envs\py37\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Anaconda\envs\py37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Anaconda\envs\py37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Program Files (x86)\DM-Count-master\datasets\crowd.py", line 124, in __getitem__
    return self.train_transform(img, keypoints)
  File "C:\Program Files (x86)\DM-Count-master\datasets\crowd.py", line 83, in train_transform
    gt_discrete = gen_discrete_map(h, w, keypoints)
  File "C:\Program Files (x86)\DM-Count-master\datasets\crowd.py", line 37, in gen_discrete_map
    discrete_map = torch.zeros(im_width * im_height).scatter_add_(0, index=p_index, src=torch.ones(im_width*im_height)).view(im_height, im_width).numpy()
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #3 'index'
Your work has given me a lot of help. Thank you very much. I really need you for this problem, and I hope to get your help.

**Comment by Summittk** [comment]
please rewrite the crowd.py line37 into the "p_index = torch.from_numpy(p_h* im_width + p_w).to(torch.int64)"
